# ----------- CONFIGURABLE START -----------
title:            "Yingge Che|ML&CV|Master Student|jekyll blog|GitHub blog"
description:      "Machine Learning & Computer Vision. Welcome to my Blog."
url:              https://yinggeche.github.io # 域名
signoff:          "Yingge Che" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Algorithms
    url:          /book
    external:     false
  - name:         Coding Skills
    url:          /road
    external:     false
  - name:         Reading Notes
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
